require('dotenv').config();
const inquirer = require('inquirer').default;
const { spawn } = require('child_process');
const path = require('path');

const processes = {};

function startProcess(name, command, args, cwd = process.cwd()) {
  if (processes[name]) {
    console.log(`${name} is already running.`);
    return;
  }

  console.log(`Starting ${name}...`);
  const child = spawn(command, args, {
    cwd,
    stdio: 'inherit',
    shell: true,
    env: { ...process.env }
  });

  processes[name] = child;

  child.on('close', (code) => {
    console.log(`${name} exited with code ${code}`);
    delete processes[name];
  });
}

function stopProcess(name) {
  if (!processes[name]) {
    console.log(`${name} is not running.`);
    return;
  }

  console.log(`Stopping ${name}...`);
  // This is a bit tricky with shell:true and cross-platform, but we'll try standard kill
  processes[name].kill();
  delete processes[name];
}

async function mainMenu() {
  const fs = require('fs');
  const chalk = require('chalk');

  console.log(chalk.blue('\n--- Environment Status ---'));
  console.log(`GOOGLE_API_KEY: ${process.env.GOOGLE_API_KEY ? 'Set' : 'MISSING'}`);
  console.log(`MODEL_NAME: ${process.env.MODEL_NAME || 'gemma-3-4b-it (default)'}`);
  console.log('--------------------------\n');

  // Inject config into PathGuardian (static HTML environment)
  const configPath = path.resolve(__dirname, '../PathGuardian/js/config.js');
  const configContent = `// Auto-generated by manage.js
window.APP_CONFIG = {
  GOOGLE_API_KEY: ${JSON.stringify(process.env.GOOGLE_API_KEY || '')},
  MODEL_NAME: ${JSON.stringify(process.env.MODEL_NAME || 'gemma-3-4b-it')}
};`;
  fs.writeFileSync(configPath, configContent);
  console.log(chalk.green(`Generated: ${configPath}`));

  const { action } = await inquirer.prompt([
    {
      type: 'list',
      name: 'action',
      message: 'Manage Unified Workspace:',
      choices: [
        { name: 'Load PathGuardian (Port 8081)', value: 'load_pg' },
        { name: 'Load BBinary (Port 5173)', value: 'load_bb' },
        { name: 'Load Sign Interpreter (Port 3000)', value: 'load_sli' },
        { name: 'Load ALL', value: 'load_all' },
        { name: '--------------------------', disabled: true },
        { name: 'Unload PathGuardian', value: 'unload_pg' },
        { name: 'Unload BBinary', value: 'unload_bb' },
        { name: 'Unload Sign Interpreter', value: 'unload_sli' },
        { name: 'Unload ALL', value: 'unload_all' },
        { name: '--------------------------', disabled: true },
        { name: 'Exit', value: 'exit' }
      ]
    }
  ]);

  switch (action) {
    case 'load_pg':
      startProcess('PathGuardian', 'npm', ['run', 'start:pg']);
      break;
    case 'load_bb':
      startProcess('BBinary', 'npm', ['run', 'start:bb']);
      break;
    case 'load_sli':
      startProcess('SignInterpreter', 'npm', ['run', 'start:sli']);
      break;
    case 'load_all':
      startProcess('PathGuardian', 'npm', ['run', 'start:pg']);
      startProcess('BBinary', 'npm', ['run', 'start:bb']);
      startProcess('SignInterpreter', 'npm', ['run', 'start:sli']);
      break;
    case 'unload_pg':
      stopProcess('PathGuardian');
      break;
    case 'unload_bb':
      stopProcess('BBinary');
      break;
    case 'unload_sli':
      stopProcess('SignInterpreter');
      break;
    case 'unload_all':
      stopProcess('PathGuardian');
      stopProcess('BBinary');
      stopProcess('SignInterpreter');
      break;
    case 'exit':
      Object.keys(processes).forEach(name => stopProcess(name));
      process.exit(0);
  }

  // Loop back to menu
  setTimeout(mainMenu, 1000);
}

console.clear();
mainMenu();
